# fly.toml app configuration file generated for backend-bitter-morning-1805 on 2026-03-02T22:37:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-bitter-morning-1805'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
